Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
f_out = './example_vid_recon.mp4'
data.render_video(f_out, wireframe=True, video=vid, verbose=False)
Video('./example_vid_recon.mp4', embed=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m f_out [38;5;241m=[39m [38;5;124m'[39m[38;5;124m./example_vid_recon.mp4[39m[38;5;124m'[39m
[0;32m----> 2[0m [43mdata[49m[38;5;241;43m.[39;49m[43mrender_video[49m[43m([49m[43mf_out[49m[43m,[49m[43m [49m[43mwireframe[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mvideo[49m[38;5;241;43m=[39;49m[43mvid[49m[43m,[49m[43m [49m[43mverbose[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m
[1;32m      3[0m Video([38;5;124m'[39m[38;5;124m./example_vid_recon.mp4[39m[38;5;124m'[39m, embed[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/medusa/core.py:672[0m, in [0;36mMediapipeData.render_video[0;34m(self, f_out, smooth, wireframe, **kwargs)[0m
[1;32m    626[0m [38;5;124;03m""" Renders a video of the reconstructed vertices. [39;00m
[1;32m    627[0m [38;5;124;03m[39;00m
[1;32m    628[0m [38;5;124;03mNote: the extension of the ``f_out`` parameter (e.g., ".gif" or ".mp4")[39;00m
[0;32m   (...)[0m
[1;32m    663[0m [38;5;124;03mTrue[39;00m
[1;32m    664[0m [38;5;124;03m"""[39;00m
[1;32m    665[0m renderer [38;5;241m=[39m Renderer(
[1;32m    666[0m     camera_type[38;5;241m=[39m[38;5;124m"[39m[38;5;124mintrinsic[39m[38;5;124m"[39m,
[1;32m    667[0m     viewport[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mimg_size,
[0;32m   (...)[0m
[1;32m    670[0m     cam_mat[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mcam_mat,
[1;32m    671[0m )
[0;32m--> 672[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrender_video[49m[43m([49m[43mf_out[49m[43m,[49m[43m [49m[43mrenderer[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mTypeError[0m: render_video() got an unexpected keyword argument 'verbose'
TypeError: render_video() got an unexpected keyword argument 'verbose'

