Traceback (most recent call last):
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/nbclient/client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
    result = await obj
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/nbclient/client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/nbclient/client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/analyse/Project0257/lukas/code/miniconda3/envs/medusa/lib/python3.10/site-packages/nbclient/client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 600 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from medusa.data import get_example_image', '', 'for p in timer_.iter(params):', '', '    if p["model_cls"] == YunetDetector and p["device"] == "cuda":']
...
['        timer_.time(model, [img], n_warmup=3, repeats=20, params=p)', '', '    torch.cuda.empty_cache()', '', 'df_detect = timer_.to_df()']
-------------------

